version: '3.8'

services:
  redis:
    image: redis:alpine
    tty: true
    ports:
      - '6379:6379'

  redis-admin:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '9001:8081'
    depends_on:
      - redis

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/fastifytodo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    depends_on:
      - redis
      - db

  db:
    image: postgres:14
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastifytodo
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
